insert into AUTHOR (id, `fname`, `lname`) values (1, 'Bayan', 'Shiryanov');
insert into AUTHOR (id, `fname`, `lname`) values (2, 'Alex', 'Pushkin');
insert into AUTHOR (id, `fname`, `lname`) values (3, 'Mike', 'Lermontov');
insert into BOOK (id, `name`, `author`, `genre`) values (1, 'Mziry', 3, 1);
insert into BOOK (id, `name`, `author`, `genre`) values (2, 'Ruslan i Lyudmila', 2, 1);
insert into BOOK (id, `name`, `author`, `genre`) values (3, 'Kapitanskaya doch', 2, 2);
insert into BOOK (id, `name`, `author`, `genre`) values (4, 'Probel', 1, 3);
insert into GENRE (id, `name`) values (1, 'Poem');
insert into GENRE (id, `name`) values (2, 'Novel');
insert into GENRE (id, `name`) values (3, 'Labuda');
