insert into AUTHOR (id, fname, lname) values (1, 'TestBayan', 'TestShiryanov');
insert into AUTHOR (id, fname, lname) values (2, 'TestAlex', 'TestPushkin');
insert into AUTHOR (id, fname, lname) values (3, 'TestMike', 'TestLermontov');
insert into GENRE (id, name) values (1, 'TestPoem');
insert into GENRE (id, name) values (2, 'TestNovel');
insert into GENRE (id, name) values (3, 'TestLabuda');
insert into USER (id) values ('TestSuperAdmin');
insert into BOOK (id, name, author_id, genre_id) values (1, 'TestMziry', 3, 1);
insert into BOOK (id, name, author_id, genre_id) values (2, 'TestRuslan i Lyudmila', 2, 1);
insert into BOOK (id, name, author_id, genre_id) values (3, 'TestKapitanskaya doch', 2, 2);
insert into BOOK (id, name, author_id, genre_id) values (4, 'TestProbel', 1, 3);
insert into COMMENT (id, book_id, user_id, comment) values (1, 4, 'TestSuperAdmin', 'TestThis book is bullshit');
