CREATE TABLE AUTHOR(ID INT PRIMARY KEY, FNAME VARCHAR(255), LNAME VARCHAR(255));
CREATE TABLE BOOK(ID INT PRIMARY KEY, NAME VARCHAR(255), AUTHOR VARCHAR(255), GENRE VARCHAR(255));
CREATE TABLE GENRE(ID INT PRIMARY KEY, NAME VARCHAR(255));