CREATE TABLE AUTHOR(ID LONG PRIMARY KEY, FNAME VARCHAR(255), LNAME VARCHAR(255));
CREATE TABLE GENRE(ID LONG PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE USER(ID VARCHAR(255));
CREATE TABLE BOOK(ID LONG PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID LONG, GENRE_ID LONG);
CREATE TABLE COMMENT(ID LONG PRIMARY KEY, BOOK_ID LONG, USER_ID VARCHAR(255), COMMENT VARCHAR(5000));
ALTER TABLE BOOK ADD CONSTRAINT BK_AUTH_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD CONSTRAINT BK_GENR_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);
ALTER TABLE COMMENT ADD CONSTRAINT CT_BOOK_ID_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);
ALTER TABLE COMMENT ADD CONSTRAINT CT_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID);