CREATE TABLE AUTHOR(ID LONG PRIMARY KEY, FNAME VARCHAR(255), LNAME VARCHAR(255));
CREATE TABLE GENRE(ID LONG PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOK(ID LONG PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID LONG, GENRE_ID LONG);
ALTER TABLE BOOK ADD CONSTRAINT BK_AUTH_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD CONSTRAINT BK_GENR_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);